Check whether current user is operations user
openshift/origin-web-common pull request #342
Opened 2018-08-22 10:21 UTC by josefkarasek

BZ: Cluster admin, click "View Archive" shows no result in Kibana
https://bugzilla.redhat.com/show_bug.cgi?id=1587807

2018-08-22 12:28 UTC, spadgett commented
I'd just include this in your origin-web-console PR. We are feature frozen and have moved new development to origin/console, so this will likely only be used for the one logging fix.

2018-08-22 12:33 UTC, spadgett requested changes

2018-08-22 12:33 UTC, spadgett commented on src/services/aggregatedLoggingService.js
> +      var deferred = $q.defer();
You shouldn't need to create a new deferred. Just return the promise from `DataService.create()` or return `$q.when(cachedValue)` when returning a cached value.

2018-08-22 12:33 UTC, spadgett commented on src/services/aggregatedLoggingService.js
> +    var cachedUserPermissions = $cacheFactory('operationsUsersCache', {
This seems like overkill since we're only ever checking one permission. It's really just one boolean value and a promise that we need to track.

2018-08-22 12:33 UTC, spadgett commented on src/services/aggregatedLoggingService.js
> +    inFlightPermissionsRequests = {};
There should only ever be one, so this doesn't need to be a map.

2018-08-22 12:33 UTC, spadgett commented on src/services/aggregatedLoggingService.js
> +        deferred.resolve();
Why aren't we returning the value in any of these `deferred.resolve()` calls?

2018-08-30 09:30 UTC, josefkarasek commented
This file is part of openshift/origin-web-console#3060

2018-08-30 09:30 UTC, closed without merging